[package]
name = "secure"
version = "0.1.0"
edition = "2021"

[dependencies]
# Dependencies for key_maker
argon2 = "0.5.3"
aes = "0.8.4"
ctr = "0.9.2"
rand = "0.8.5"
rand_chacha = "0.3.1"
zeroize = "1.8.1"

